version: '3.8'
services:
  api-server:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123456
      POSTGRES_DB: music
    networks:
      - musicserver
networks:
  musicserver:
