version: '3.8'
services:
  api-server:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    networks:
      - musicserver
networks:
  musicserver:
